default:
  - 'clean'
  - 'copy'
  - 'sass'
#  - 'autoprefixer'
  - 'cmq'
  - 'cssmin'
  # - 'browserify'
  # - 'jshint'
  # - 'uglify'
  - htmlmin

dev:
  - 'sass'
  - 'cmq'
  - 'cssmin'
  # - 'browserify'
  # - 'uglify'
  - htmlmin

server:
  - connect
  - watch

test:
  - karma
